CREATE TABLE crime_rel_2(
   Year      INTEGER  
  ,GEOGRAPHY VARCHAR(77) 
,FOREIGN KEY (Year) REFERENCES crime_safety_home_alone(Year)
,FOREIGN KEY (GEOGRAPHY) REFERENCES crime_stastics_year(GEOGRAPHY)
);
INSERT INTO crime_rel_2(Year,GEOGRAPHY) VALUES
 (2007,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(2008,'Stellarton, Nova Scotia, municipal')
,(2009,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(2010,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(2011,'Amherst, Nova Scotia, municipal')
,(2012,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(2013,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(2014,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(2015,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(2016,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(2017,'Bridgewater, Nova Scotia, municipal')
,(2018,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Nova Scotia')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Nova Scotia')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Nova Scotia')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Truro, Nova Scotia, municipal');
INSERT INTO crime_rel_2(Year,GEOGRAPHY) VALUES
 (NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Nova Scotia')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Nova Scotia')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural');
INSERT INTO crime_rel_2(Year,GEOGRAPHY) VALUES
 (NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Nova Scotia')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Colchester County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Amherst, Nova Scotia, municipal')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Shelburne, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Nova Scotia');
INSERT INTO crime_rel_2(Year,GEOGRAPHY) VALUES
 (NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Cape Breton Region, Nova Scotia, municipal')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Truro, Nova Scotia, municipal')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Pictou County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Antigonish County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Nova Scotia')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis Royal, Nova Scotia, municipal')
,(NULL,'Indian Brook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 2), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port Hawkesbury, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Westville, Nova Scotia, municipal')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Meteghan (Clare), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Millbrook, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Victoria County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Enfield (East Hants), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (Division Headquarters 1), Nova Scotia, Royal Canadian Mounted Police')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Lunenburg County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Port of Halifax, Nova Scotia, Ports Canada Police')
,(NULL,'Antigonish, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Barrington, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Bridgewater, Nova Scotia, municipal')
,(NULL,'Springhill, Nova Scotia, municipal')
,(NULL,'Oxford County, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Queens County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'New Glasgow Region, Nova Scotia, municipal')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Eskasoni, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Trenton, Nova Scotia, municipal')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Stellarton, Nova Scotia, municipal')
,(NULL,'Richmond County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Kentville, Nova Scotia, municipal')
,(NULL,'Pictou, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Halifax (offshore), Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Inverness County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Canadian National Railway Police, Nova Scotia')
,(NULL,'Halifax Metropolitain Area, Nova Scotia, municipal')
,(NULL,'Kings County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Guysborough County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Yarmouth, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Cumberland County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Annapolis County, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Parrsboro, Nova Scotia, Royal Canadian Mounted Police, municipal')
,(NULL,'Windsor, Nova Scotia, Royal Canadian Mounted Police, rural')
,(NULL,'Digby, Nova Scotia, Royal Canadian Mounted Police, municipal');
