CREATE TABLE life_2(
   Gaelic_language_and_cultural_and_supporting_organizations VARCHAR(77) 
  ,Community                                                 VARCHAR(75)
,FOREIGN KEY (Gaelic_language_and_cultural_and_supporting_organizations) REFERENCES gaelicorganization_new(Gaelic_language_and_cultural_and_supporting_organizations)
,FOREIGN KEY (Community) REFERENCES communities_new(Community)
);
INSERT INTO life_2(Gaelic_language_and_cultural_and_supporting_organizations,Community) VALUES
 ('Whycocomagh and District Historical Society','Municipality of the District of Chester')
,('Inverness Development Agency','Town of Mahone Bay')
,('Celtic Culture and Gaelic, Cape Breton University','Town of Bridgewater')
,('Comann FÃ©is an Eilein / Christmas Island Festival Society','Municipality of the District of Argyle')
,('GÃ idhlig Agam / I Speak Gaelic Society','Municipality of the District of Yarmouth')
,('Colaisde na GÃ idhlig / Gaelic College','Municipality of the District of Digby in partnership with the Town of Digby')
,('Strathspey Place','Municipality of the District of Digby in partnership with the Town of Digby')
,('Comhairle na GÃ idhlig / The Gaelic Council of Nova Scotia','Municipality of the County of Cumberland')
,('Celtic Cultural Society of Pictou County','Municipality of the County of Cumberland')
,('Historic Sherbrooke Village Development Society','Town of New Glasgow in partnership with the Municipality of Pictou County')
,('An Comann Ceilteach St.F.X. / Celtic Society St.F.X.','Town of New Glasgow in partnership with the Municipality of Pictou County')
,('Special Collections, St.F.X. University','Municipality of the District of Guysborough')
,('St. Francis Xavier Celtic Studies Department','Municipality of the County of Richmond')
,('The Ships of 1801 Society','Municipality of the County of Victoria')
,('North Highlands Community Organization',NULL)
,('Celtic Cultural Society of Nova Scotia',NULL)
,('The Federation of Scottish Culture',NULL)
,('The St. Andrew''s Society of Pictou County',NULL)
,('Mabou Gaelic & Historical Society',NULL)
,('Baile nan GÃ idheal / Nova Scotia Highland Village',NULL)
,('Celtic Colours',NULL)
,('Celtic Music Interpretive Centre',NULL)
,('Centre for European Studies, Dalhousie University',NULL)
,('Irish Studies Department, Saint Mary''s University',NULL)
,('North Shore Gaelic Heritage Society',NULL)
,('Antigonish Highland Society',NULL)
,('Sgoil GÃ idhlig an Ard Bhaile / Halifax Gaelic Language Society',NULL)
,('Comann GÃ idhlig Antaiginis / Antigonish Gaelic Society',NULL)
,('Comann FÃ©is MhÃ bu / Mabou Festival Society',NULL)
,('Sgoil GhÃ idhlig Baile a'' Chlamhain / Port Hawkesbury Gaelic Language Society',NULL)
,('Comann GÃ idhlig Cheap Breatuinn / Cape Breton Gaelic Society',NULL)
,('Festival of the Tartans',NULL)
,('Westmount Gaelic Society',NULL)
,('New Trad Society',NULL)
,('Pictou County Roots Society',NULL)
,('Hector Heritage Quay',NULL)
,('The Scots',NULL);
