CREATE TABLE life_1(
   Programs  VARCHAR(42) 
  ,Community VARCHAR(75)
,FOREIGN KEY (Programs) REFERENCES myarts(Programs)
,FOREIGN KEY (Community) REFERENCES communities(Community)
);
INSERT INTO life_1(Programs,Community) VALUES
 ('Grants to Organizations and Small Groups','Municipality of the District of Chester')
,('Grants to Individuals','Town of Mahone Bay')
,('Operating Assistance to Arts Organizations','Town of Bridgewater')
,('Project Grants for Publishing Program','Municipality of the District of Argyle')
,('Art Bank','Municipality of the District of Yarmouth')
,('Art Bank (Operations)','Municipality of the District of Digby in partnership with the Town of Digby')
,('Artists in Schools','Municipality of the District of Digby in partnership with the Town of Digby')
,('Portia White Prize','Municipality of the County of Cumberland')
,('Grand Pre Prize','Municipality of the County of Cumberland')
,('Lieut. Governor''s Masterworks Award','Town of New Glasgow in partnership with the Municipality of Pictou County')
,('Talent Trust','Town of New Glasgow in partnership with the Municipality of Pictou County')
,('Confederation Center','Municipality of the District of Guysborough')
,('NSCAD Gordon Parsons Award','Municipality of the County of Richmond')
,('Arts Equity Program','Municipality of the County of Victoria')
,('Artistic Innovation Program',NULL)
,('Creative Collaborations Program',NULL)
,('Salaries',NULL)
,('Arts NS Operations',NULL)
,('Grants to Organizations and Small Groups',NULL)
,('Grants to Individuals',NULL)
,('Operating Assistance to Arts Organizations',NULL)
,('Project Grants for Publishing Program',NULL)
,('Art Bank',NULL)
,('Art Bank (Operations)',NULL)
,('Artists in Schools',NULL)
,('Portia White Prize',NULL)
,('Grand Pre Prize',NULL)
,('Lieut. Governor''s Masterworks Award',NULL)
,('Talent Trust',NULL)
,('Confederation Center',NULL)
,('NSCAD Gordon Parsons Award',NULL)
,('Arts Equity Program',NULL)
,('Artistic Innovation Program',NULL)
,('Creative Collaborations Program',NULL)
,('Salaries',NULL)
,('Arts NS Operations',NULL);
