CREATE TABLE program_est_rel(
   Account_Name VARCHAR(66) 
  ,ComID        VARCHAR(7)
,FOREIGN KEY (Account_Name) REFERENCES business_development(Account_Name)
,FOREIGN KEY (ComID) REFERENCES business_establishments(ComID)
);
INSERT INTO program_est_rel(Account_Name,ComID) VALUES
 ('Northern Business Intelligence','pro9046')
,('Fourth State Energy Incorporated','can')
,('Skinfix Inc','can')
,('Singolar Inc','cnt1201')
,('Truro Herbal Co.','cnt1201')
,('SimplyCast Interactive Marketing LTD.','cnt1202')
,('En Point Inc','cnt1202')
,('BlueLight Analytics Inc','cnt1203')
,('Ednaturals Bar','cnt1203')
,('Victoria Co-Operative Fisheries Ltd','cnt1204')
,('Focal Technologies Corporation','cnt1204')
,('Cove Kombucha','cnt1205')
,('Dormie Golf Workshop Inc.','cnt1205')
,('B4Checkin Limited','cnt1206')
,('Barrelling Tide Distillery','cnt1206')
,('Fundmetric Incorporated','cnt1207')
,('Ven-Rez Products Ltd','cnt1207')
,('Riverside Lobster International Inc','cnt1208')
,('Precision BioLogic Incorporated','cnt1208')
,('Duckish Natural Skin Care Limited','cnt1209')
,('GeoNavo Positioning Systems Inc','cnt1209')
,('Eyeread Inc.','cnt1210')
,('WarrierTech Inc','cnt1210')
,('Unleash Surf Inc.','cnt1211')
,('THE WELL - CREATIVE CONSULTANTS INC.','cnt1211')
,('BMC Seafoods Ltd','cnt1212')
,('Atlantic Institute for Resilience Inc.','cnt1212')
,('Cribcut','cnt1213')
,('Sealand Building Group Inc','cnt1213')
,('Keeping Roads Safe Technologies Inc','cnt1214')
,('Tony''s Meats Ltd','cnt1214')
,('Stark International Inc','cnt1215')
,('Made with Local Snack Foods Inc.','cnt1215')
,('BioMedica Diagnostics Inc','cnt1216')
,('InterTalk Critical Information Systems Inc','cnt1216')
,('Bend Beauty Inc.','cnt1217')
,('Hanatech IOT Inc.','cnt1217')
,('Chocolate Hackers','cnt1218')
,('Terra Beata','cnt1218')
,('DBR Resources LTD.','ecr21')
,('Grey Lit Matters Inc','ecr21')
,('DynaGen Technologies Incorporated','ecr22')
,('Classic Fine Foods','ecr22')
,('Spark Engagement Inc','ecr23')
,('Marcato Digital Solutions Inc','ecr23')
,('EfficiencyOne Services Inc','ecr24')
,('3231974 NOVA SCOTIA LIMITED o/a Do Lobster','ecr24')
,('Bereda Training Inc.','ecr25')
,('Iris Booth Incorporated','ecr25')
,('Densitas Inc','pro9010')
,('Atlantic Sea Cucumber Ltd','pro9010')
,('Rx Security Inc.','pro9011')
,('Tangled Garden','pro9011')
,('Advanced Glazings Ltd','pro9012')
,('Benjamin Bridge Vineyards','pro9012')
,('Rotofast Inc','pro9013')
,('Novate Systems Inc.','pro9013')
,('Safety Made Easy Basic Training','pro9024')
,('Allendale Electronics Ltd','pro9024')
,('MindSea Development Incorporated','pro9035')
,('Just Us! Coffee Roasters Co-op Ltd','pro9035')
,('Site 2020 Inc.','pro9046')
,('Athletigen Technologies Inc','pro9047')
,('Spring Loaded Technology Incorporated','pro9047')
,('Boondoc Technologies Inc (The Rounds)','pro9048')
,('Dragon Veterinary Canada Limited','pro9048')
,('The 7 Virtues Beauty Inc','pro9059')
,('902HipHop Inc.','pro9059')
,('Sales Beacon','pro9060')
,('MetOcean Telematics Limited','pro9060')
,('Peace by Chocolate Inc.','pro9061')
,('Blue Harbour Cheese Incorporated','pro9061')
,('Novonix Battery Testing Services Inc','pro9062')
,('InnovaSea Marine Systems Canada Inc DBA Vemco','pro9062')
,('Current Studios Inc',NULL)
,('Live Stor Sydney Limited',NULL)
,('R&G Strategic Inc',NULL)
,('Scope Digital Media',NULL)
,('Skye Larke Productions Limited',NULL)
,('Talem Health Analytics Inc',NULL)
,('Digital Cinema Labs Inc.',NULL)
,('Roswall Development Incorporated',NULL)
,('EcoPilot Canada Inc.',NULL)
,('Accomplice Content Supply Co., Inc.',NULL)
,('Beyond Food Inc.',NULL)
,('Chain-Yard Cider Inc',NULL)
,('Content Bloom Inc',NULL)
,('East Coast School of Languages (ECSL)',NULL)
,('Eli Technology',NULL)
,('Jaza Energy Inc.',NULL)
,('Kula Partners Inc.',NULL)
,('Lisa Young Lee Inc.',NULL)
,('McFadgen''s Bakery Limited',NULL)
,('Mercator Geological Services Limited',NULL)
,('Mobia Technology Innovations',NULL)
,('Pictou Twist Pictures Inc',NULL)
,('PitchPerfect Software Inc. operating as Proposify',NULL)
,('RIMOT.IO Inc',NULL)
,('Sand To Sky Productions',NULL)
,('Seafoam Lavender Company',NULL);
INSERT INTO program_est_rel(Account_Name,ComID) VALUES
 ('Shift',NULL)
,('Steinhart Distillery Limited',NULL)
,('Synclavier Digital Corporation Ltd.',NULL)
,('Ultra Electronics Maritime Systems',NULL)
,('Waterstar Entertainment Inc.',NULL)
,('Waycobah Contracting Incorporated',NULL)
,('Afishionado Fish Mongers Inc',NULL)
,('Bluedrop Training & Simulation Inc.',NULL)
,('Compass Distillers',NULL)
,('Muwin Estate Wines Ltd',NULL)
,('The Soap Company of Nova Scotia Ltd',NULL)
,('Topsail Productions Ltd.',NULL)
,('2 Crows Brewing Ltd',NULL)
,('Baie Run Pet Products Inc',NULL)
,('Cartoon Conrad Productions Inc',NULL)
,('Fit First Holdings Inc.',NULL)
,('Imaginal Ventures Inc.',NULL)
,('JusNova Agriculture Ltd',NULL)
,('Stratigro Business Consulting',NULL)
,('4Deep Inwater Imaging',NULL)
,('Blois Fish Processing Automation Limited',NULL)
,('Maritime Gourmet Mushrooms Inc',NULL)
,('Atlantic Flight Attendant Academy',NULL)
,('Breton Brewing Co',NULL)
,('Lunenburg County Shipwrights Inc.',NULL)
,('Raised Performance Media Inc.',NULL)
,('SalesRight Technologies Inc',NULL)
,('Sayle Group Inc',NULL)
,('Youx Systems Inc.',NULL)
,('6 Joe''s Software Inc.',NULL)
,('Downeast Entertainment & Meeting Specialists Limited',NULL)
,('Hand Maiden Fine Yarn Inc.',NULL)
,('Maritime bioLoggers Inc.',NULL)
,('Momentum IT Group',NULL)
,('New Colliers Ltd',NULL)
,('Pelagis Data Solutions',NULL)
,('Ziah Frost Media Inc.',NULL)
,('Breakers Fish Co Ltd',NULL)
,('FoodByte Inc',NULL)
,('Foundation Marketing Services Inc.',NULL)
,('Graphite Innovation and Technologies Inc.',NULL)
,('Mimir Networks Corporation',NULL)
,('Portara Pictures Incorporated',NULL)
,('Securicy Data Solutions Ltd',NULL)
,('Sedna Tech',NULL)
,('Strongest Families Institute',NULL)
,('Success Through Trust Inc',NULL)
,('Deprolabs Technology Inc.',NULL)
,('Dominion Diving Limited',NULL)
,('Festina Lente Productions Inc.',NULL)
,('Focal Research Consultants Limited',NULL)
,('Harbr Inc.',NULL)
,('Leeway Yachts Ltd.',NULL)
,('NS Sports Media Pros Ltd',NULL)
,('Prosaris Consulting Ltd.',NULL)
,('QRA Corp',NULL)
,('Peer Ledger Inc',NULL)
,('Acoubit Communications',NULL)
,('Meghan Martin Incorporated',NULL)
,('MRE Industries Limited',NULL)
,('Nova Graphene',NULL)
,('PeopleCan Training & Development',NULL)
,('World Link Food Distributors Inc',NULL)
,('CacheFlo Inc.',NULL)
,('Guild Software Inc',NULL)
,('Nodalblock Canada Holdings Inc.',NULL)
,('Panag Pharma Inc.',NULL)
,('Ubique Networks Inc',NULL)
,('Clerisy Management Group Limited',NULL)
,('Dadavan Systems Inc',NULL)
,('East Coast Varsity',NULL)
,('Hivetronics Limited',NULL)
,('More In Store Marketing Solutions Inc',NULL)
,('NewAE Technology Inc.',NULL)
,('SolutionInc Ltd',NULL)
,('Chase''s Lobster Pound Ltd',NULL)
,('Survival Systems Ltd',NULL)
,('Two East Productions Inc.',NULL)
,('Deep Vision Inc',NULL)
,('DGI Clinical Inc.',NULL)
,('Du Nord Skin Care',NULL)
,('Halifax Language Institute of Canada',NULL)
,('Proven Marketing for Lawyers Inc.',NULL)
,('Sassy Solutions Consulting Limited',NULL)
,('Trip Ninja',NULL)
,('Tri-Star Industries Limited',NULL)
,('Uprise Consulting',NULL)
,('USP-LAB N.A. Ltd.',NULL)
,('AC Live Lobster Inc',NULL)
,('Beta Glucan Company of Canada Inc.',NULL)
,('CarbonCure Technologies Inc',NULL)
,('Giffin Technologies Inc.',NULL)
,('Huminah Huminah Animation',NULL)
,('Oyster Promo Inc',NULL)
,('Picture Plant Ltd.',NULL)
,('The Instratify Group Inc.',NULL)
,('Access Labels',NULL)
,('Iron Apple',NULL)
,('SailTimer Inc.',NULL)
,('Skyline (Refer to Orgrimmar Tech. Inc.)',NULL);
INSERT INTO program_est_rel(Account_Name,ComID) VALUES
 ('Survival Systems Training Limited',NULL)
,('Dugo Systems Inc',NULL)
,('Journeyman Film Company  Ltd.',NULL)
,('TapRoot Fibre Lab Inc',NULL)
,('Eel Lake Oyster Farm',NULL)
,('MacGregors Industrial Group',NULL)
,('Pivotal Coaching',NULL)
,('Arcadia Entertainment Inc.',NULL)
,('Burnt Out Solutions Inc',NULL)
,('EcoAdvisors Inc',NULL)
,('Stantec',NULL)
,('Dillon Consulting Ltd',NULL)
,('McGlone Sales and Consulting',NULL)
,('Stright-MacKay Ltd',NULL)
,('AGL Group Holding Limited',NULL)
,('Arrivals + Departures Communications Limited',NULL)
,('Breton SmarTek Inc',NULL)
,('Eosense Inc',NULL)
,('Fossil Power Systems Inc.',NULL)
,('LearnCorp International',NULL)
,('Sailing CBI Inc',NULL)
,('Bad Fem Productions Inc.',NULL)
,('Colibri Software',NULL)
,('Halifax Glassworks Limited',NULL)
,('Modest Tree Media Inc',NULL)
,('SEG Consulting Inc.',NULL)
,('Shut Up & Colour Pictures Inc',NULL)
,('Swept Technologies Inc.',NULL)
,('WoodChaCallIt Toy and Wood Crafters',NULL)
,('ProNova Marine Products Limited',NULL)
,('VitaMed Inc',NULL)
,('Core Elements Advisors Inc.',NULL)
,('Andrew MacCormack',NULL)
,('Aqua Production Systems Incorporated',NULL)
,('Nexus Coastal Resource Management',NULL)
,('Over The Edge (Canada) Inc',NULL)
,('Pro-Oceanus Systems Inc',NULL)
,('Sober Island Oysters Limited',NULL)
,('My Home Apparel',NULL)
,('Social Navigator Inc',NULL)
,('Eye Catch Signs Limited',NULL)
,('Flo Digital Inc',NULL)
,('Sea to Sea Productions Ltd.',NULL)
,('Turbulent Research Inc',NULL)
,('Xeos Technologies Inc',NULL)
,('APPILI Therapeutics',NULL)
,('Black Star Wealth Partners',NULL)
,('Cabbage Patch Kimchi',NULL)
,('Gorgeous Mistake Productions',NULL)
,('Nautics Group Inc.',NULL)
,('Nu-Air Ventilation Systems Inc',NULL)
,('Ocean Sonics Ltd',NULL)
,('Retail Deep',NULL)
,('Rebel Road Films',NULL)
,('Climate Technical Gear',NULL)
,('Freshify Inc',NULL)
,('Midgard Insect Farm Inc',NULL)
,('Ocean Pride Fisheries Limited (Atlantic Treasure Limited)',NULL)
,('Vesuvius Media Ltd.',NULL)
,('EOceans Research and Consulting Inc.',NULL)
,('I Matheson & Company (IMC) Ltd',NULL)
,('Enginuity Inc.',NULL)
,('Fourth Wave Strategy Inc',NULL)
,('Romor Ocean Solutions',NULL)
,('Schoolhouse Gluten Free Gourmet Ltd.',NULL)
,('Spritely Technologies Inc',NULL)
,('Green Power Labs Inc',NULL)
,('Andrea Janzen Professional Coaching',NULL)
,('Atlantic Ambassatours Ltd.',NULL)
,('Left Meets Right Creative Co',NULL)
,('RPS Composites Inc',NULL)
,('Ruby Tree Films Inc.',NULL)
,('Black Dog Films / The Monster Productions Inc',NULL)
,('GN Plastics Company Ltd.',NULL)
,('Nautel Limited',NULL)
,('Efficiency Properties',NULL)
,('Aerovision Canada',NULL)
,('Glas Ocean Electric Inc',NULL)
,('Red Dragon Marketing',NULL)
,('Canada Rope & Twine Limited',NULL)
,('Hoppy''s Safety Hook Enterprise',NULL)
,('Lorax Systems Inc',NULL)
,('Manage Your Spend',NULL)
,('Outdoor-Fit Exercise Systems',NULL)
,('Side Door Access Inc',NULL)
,('Smarter Spaces Inc',NULL)
,('Omnitech Electronics Inc',NULL)
,('TerraProForma (FORMERLY - Play the Field)',NULL)
,('Javitech Atlantic Ltd',NULL)
,('Allswater Marine Consultants Ltd',NULL)
,('Atlantic Prepaid',NULL)
,('Blue Ocean Contact Centers',NULL)
,('Cut/Off/Tail Pictures',NULL)
,('First Catch Fisheries Co. Ltd',NULL)
,('Ocean Perfect North America Inc.',NULL)
,('SOHMA Naturals',NULL)
,('The Discovery Centre International Inc.',NULL)
,('The Family Knife Marketing Consultancy Inc.',NULL)
,('Twirp Communications',NULL)
,('Vertical Productions Inc.',NULL);
INSERT INTO program_est_rel(Account_Name,ComID) VALUES
 ('Atlantex Limited',NULL)
,('Bandha Nutrition Products',NULL)
,('Boxing Rock Brewing Co',NULL)
,('Dynamic Systems Analysis Ltd.',NULL)
,('Magic Rock Productions',NULL)
,('Mersey Consulting Ltd',NULL)
,('Mil-Aero Electronics Atlantic Inc',NULL)
,('Partner International Inc',NULL)
,('Capital Seafood International Incorporated',NULL)
,('Aerotec Engines Limited',NULL)
,('CBCL Limited',NULL)
,('Tucan Olive Oil Company Ltd',NULL)
,('BlockCrushr Inc.',NULL)
,('C Squared Project Management Services Ltd.',NULL)
,('Copernicus Labs Inc',NULL)
,('Innovative Fishery Products Inc',NULL)
,('ITO Seafoods Ltd',NULL)
,('Nautical Seafoods Ltd',NULL)
,('Prism Tradeshow Products Inc.',NULL)
,('Sufata Software Solutions, Inc',NULL)
,('Uplift Content Inc',NULL)
,('Verb Interactive Inc.',NULL)
,('Wired Flare Inc',NULL)
,('Ocean Entertainment Ltd.',NULL)
,('Pisces Research Project Management Inc',NULL)
,('Web Builders Group Inc',NULL)
,('HB Studios Multimedia Ltd',NULL)
,('Dartmouth Metals and Bottle Limited',NULL)
,('Kenney & Ross, Limited',NULL)
,('Ocean Crisp Apple Company Incorporated',NULL)
,('Surrette Battery Company Limited',NULL)
,('John Ross & Sons Ltd.',NULL)
,('Canadian Maritime Engineering Limited',NULL)
,('Maritime Labels & Packaging',NULL)
,('Kohltech International Ltd',NULL)
,('Agropur Cooperative',NULL)
,('Scotian Gold Cooperative Ltd',NULL)
,('Oxford Frozen Foods Ltd',NULL)
,('Michelin North America (Canada) Inc - Granton',NULL)
,('AF Theriault & Son Ltd.',NULL)
,('Kilo Communications Inc',NULL)
,('The Lobster Trap Company Limited',NULL)
,('Airesun Global Limited',NULL)
,('Photodynamic Incorporated',NULL)
,('NeoThermal Energy Storage Inc',NULL)
,('Scotia Garden Seafoods Inc',NULL)
,('Axem Neurotechnology Inc.',NULL)
,('Nova Aquaponics Incorporated',NULL)
,('Louisbourg Seafoods Ltd',NULL)
,('Aurea Technologies Inc',NULL)
,('D.M.R. Boat Design Limited',NULL)
,('Cape Breton Bivalve Inc',NULL)
,('Velsoft Training Materials Inc',NULL)
,('F L Action/Reaction Sports',NULL)
,('Heritage Memorials Limited',NULL)
,('Chelation Partners Incorporated',NULL)
,('Dykeview Farms Limited',NULL)
,('Fundy Hops',NULL)
,('Atlantick Repellent Products Inc.',NULL)
,('Saltbox Brewing Company',NULL)
,('Sea-Pur Seaweed Products',NULL)
,('Alto Solar',NULL)
,('Natural Ocean Products Inc.',NULL)
,('RGI Logistics & Technology Inc.',NULL)
,('L''Acadie Vineyards',NULL)
,('Stevens Solutions & Design Inc',NULL)
,('Bear River Vineyards Ltd.',NULL)
,('Mermaid Fare Inc',NULL)
,('ColorSmith',NULL)
,('Bear Cove Resources',NULL)
,('Defenzall Therapeutics Inc.',NULL)
,('Finleaf Technologies Inc.',NULL)
,('Stones Pharmacy',NULL)
,('Propel BioEnergy LTD.',NULL)
,('Apaqtaukewaq Fishery Co-op',NULL)
,('PPT Labs Inc.',NULL)
,('NovaResp Technologies Inc.',NULL)
,('Elcora Advanced Materials Corp',NULL)
,('Yarmouth Bar Fisheries Limited',NULL)
,('LED Roadway Lighting Ltd',NULL)
,('Copol International Ltd.',NULL)
,('Introhive Services (NS) Inc.',NULL)
,('The Sydney Call Centre Inc.',NULL)
,('REDspace Inc',NULL)
,('Influitive Corporation',NULL)
,('Savormetrics Inc.',NULL)
,('Monkedia LLC',NULL)
,('Manulife Financial',NULL)
,('Dilytics',NULL)
,('BeyondTrust Software Inc.',NULL)
,('10380008 Canada Inc dba MobSquad',NULL)
,('Gael Force Group',NULL)
,('Sensor Technology Ltd',NULL)
,('Columbus AI',NULL)
,('Accenture Canada',NULL)
,('Propipe UK',NULL)
,('Invisible Agents',NULL)
,('Nova Innovation',NULL)
,('Sea Harvest Seafood (2019) Ltd',NULL)
,('Adadem Import and Export',NULL);
INSERT INTO program_est_rel(Account_Name,ComID) VALUES
 ('Amos And Andy Fisheries Limited',NULL)
,('Caldera Distilling Inc.',NULL)
,('Clever Fruit Products',NULL)
,('Fair Grant Writing',NULL)
,('Famolex Integrated Consult Limited',NULL)
,('Globiz Innovation Inc.',NULL)
,('McInnes Cooper',NULL)
,('Sea Star Seafoods Limited',NULL)
,('GeoSpectrum Technologies Incorporated',NULL)
,('Institute for Big Data Analytics',NULL)
,('Jasco Applied Sciences (Canada) Ltd',NULL)
,('Kraken Robotics Inc.',NULL)
,('Metamaterial Technologies Inc',NULL)
,('Acadian Maple Products Ltd',NULL)
,('Acadian Seaplants Limited / Les Algues Acadiennes Limitee',NULL)
,('Cedar Bay Grilling Company',NULL)
,('Galloping Cows Fine Foods',NULL)
,('Hailmar Investments Limited',NULL)
,('Hutchinson Maple (Hutchinson Acres Inc) (Pure Infused Maple Syrup)',NULL)
,('The Tea Brewery',NULL)
,('Van Dyk''s Health Juice Products Ltd',NULL)
,('Luckett Vineyards (Luckett Farms Limited)',NULL)
,('Blomidon Estate Winery',NULL)
,('Devonian Coast Wineries Ltd  (DCW)',NULL)
,('Domaine de Grand Pre',NULL)
,('Mother Hubbard''s Kitchens',NULL)
,('Bluenose Frozen Seafood Incorporated',NULL)
,('Captain Little Seafood Ltd.',NULL)
,('Marimetrics Technologies',NULL)
,('Ocean Data Science',NULL)
,('Prosaris Solutions Ltd.',NULL)
,('ReelData',NULL)
,('Wittaya Aqua',NULL)
,('Geoforce Group Limited',NULL)
,('MacArtney Canada Ltd',NULL)
,('Clearwater Seafoods Ltd Partnership',NULL)
,('Gidney Fisheries Limited',NULL)
,('Natural Hues Inc',NULL)
,('Ashored Innovations',NULL)
,('Annapolis Brewing Company',NULL)
,('Authentic Seacoast Company Ltd',NULL)
,('Island_ Folk_ Cider_ House',NULL)
,('The Propeller Brewing Company',NULL)
,('IBM Canada Ltd',NULL)
,('Easypass Immigration & Education Consulting Inc',NULL)
,('Fundy Drinks LTD',NULL)
,('Sainte-Famille Wines Ltd',NULL)
,('Atlantic Resources Partnership Inc',NULL)
,('Fisher King Seafoods Ltd',NULL)
,('Right Source Group Limited',NULL)
,('Rio Import & Export Limited',NULL)
,('Top Claw Lobster & Seafood Company',NULL)
,('Hawboldt Industries (1989) Ltd',NULL)
,('Ocean Technology Council of Nova Scotia (OTCNS)',NULL)
,('Taste of Nova Scotia Quality Food',NULL)
,('Penny Doherty Literacy Consultants Incorporated',NULL)
,('Haskapa',NULL)
,('Atlantica Mechanical Contractors Inc',NULL)
,('Biscay Seafoods Canada Ltd',NULL)
,('Pearlmark Foods - NS Division',NULL)
,('Zeus Seafood Inc',NULL)
,('TriNav Fisheries Consultants Inc',NULL)
,('Realtime Aquaculture',NULL)
,('Clearwater Fine Foods (Europe) Ltd',NULL)
,('Bezanson & Chase Cranberry Co Ltd',NULL)
,('Kings Produce Processing Limited',NULL)
,('TAPROOT FARMS',NULL)
,('The Nova Agri Group',NULL)
,('Van Meekeren Farms Ltd',NULL)
,('Addvocacy ADHD & Life Skills Coaching Ltd',NULL)
,('Clockk.Com Inc',NULL)
,('Ethical Swag Inc',NULL)
,('OnBook - Port Tack Media (10527602 Canada Inc)',NULL)
,('Fishermen''s Premium Atlantic Lobster Inc',NULL)
,('Golden Alliance Canada Inc',NULL)
,('IMO Foods Limited',NULL)
,('West Fish Canada Limited',NULL)
,('Marwood Limited',NULL);
